[config]
schemaVersion = "0.0.1"

[package]
namespace = "rectorado"
name = "FontUpdate"
description = "Updates LC's font, adding the expanded latin unicode characters list."
websiteUrl = ""
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"
[[build.copy]]
source = "./build"
target = "plugins/"
[[build.copy]]
source = "./LICENSE"
target = "/"
[[build.copy]]
source = "./assets"
target = "config/"

[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company" ]
[publish.categories]
lethal-company = [ "bepinex", "client-side", "tools", "misc" ]
